### PR TITLE
Adding axis::ariable

### PR DESCRIPTION
**Pull request by henryiii**
This currently cases the following error:

<details><summary>
Click to expand
</summary>

```
In file included from /Users/henryiii/git/software/histogram-python/src/histogram/histogram.cpp:10:
In file included from /Users/henryiii/git/software/histogram-python/include/boost/histogram/python/axis.hpp:7:
In file included from /Users/henryiii/git/software/histogram-python/extern/histogram/include/boost/histogram.hpp:25:
In file included from /Users/henryiii/git/software/histogram-python/extern/histogram/include/boost/histogram/algorithm/project.hpp:12:
In file included from /Users/henryiii/git/software/histogram-python/extern/histogram/include/boost/histogram/histogram.hpp:10:
In file included from /Users/henryiii/git/software/histogram-python/extern/histogram/include/boost/histogram/detail/axes.hpp:12:
In file included from /Users/henryiii/git/software/histogram-python/extern/histogram/include/boost/histogram/axis/variant.hpp:24:
/Users/henryiii/git/software/histogram-python/extern/variant/include/boost/variant/variant.hpp:1733:9: error: call to member function
      'convert_construct' is ambiguous
        convert_construct(operand, 1L);
        ^~~~~~~~~~~~~~~~~
/Users/henryiii/git/software/histogram-python/extern/histogram/include/boost/histogram/axis/variant.hpp:235:59: note: in instantiation of
      function template specialization 'boost::variant<boost::histogram::axis::regular<double, boost::use_default, boost::use_default,
      boost::use_default>, boost::histogram::axis::regular<double, boost::use_default, boost::use_default,
      boost::histogram::axis::option::bitset<0> >, boost::histogram::axis::regular<double, boost::histogram::axis::transform::id,
      boost::use_default, boost::histogram::axis::option::bitset<6> >, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::log, boost::use_default, boost::use_default>, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::pow, boost::use_default, boost::use_default>, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::sqrt, boost::use_default, boost::use_default>, boost::histogram::axis::variable<double,
      boost::use_default, boost::use_default, std::__1::allocator<double> >
      >::variant<boost::histogram::axis::variant<boost::histogram::axis::regular<double, boost::use_default, boost::use_default,
      boost::use_default>, boost::histogram::axis::regular<double, boost::use_default, boost::use_default,
      boost::histogram::axis::option::bitset<0> >, boost::histogram::axis::regular<double, boost::histogram::axis::transform::id,
      boost::use_default, boost::histogram::axis::option::bitset<6> >, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::log, boost::use_default, boost::use_default>, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::pow, boost::use_default, boost::use_default>, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::sqrt, boost::use_default, boost::use_default>, boost::histogram::axis::variable<double,
      boost::use_default, boost::use_default, std::__1::allocator<double> > > >' requested here
  return boost::apply_visitor(std::forward<Visitor>(vis), static_cast<B>(var));
                                                          ^
/Users/henryiii/git/software/histogram-python/extern/pybind11/include/pybind11/stl.h:317:16: note: in instantiation of function template
      specialization 'boost::histogram::axis::visit<pybind11::detail::variant_caster_visitor,
      boost::histogram::axis::variant<boost::histogram::axis::regular<double, boost::use_default, boost::use_default, boost::use_default>,
      boost::histogram::axis::regular<double, boost::use_default, boost::use_default, boost::histogram::axis::option::bitset<0> >,
      boost::histogram::axis::regular<double, boost::histogram::axis::transform::id, boost::use_default,
      boost::histogram::axis::option::bitset<6> >, boost::histogram::axis::regular<double, boost::histogram::axis::transform::log,
      boost::use_default, boost::use_default>, boost::histogram::axis::regular<double, boost::histogram::axis::transform::pow,
      boost::use_default, boost::use_default>, boost::histogram::axis::regular<double, boost::histogram::axis::transform::sqrt,
      boost::use_default, boost::use_default>, boost::histogram::axis::variable<double, boost::use_default, boost::use_default,
      std::__1::allocator<double> > > >' requested here
        return visit(std::forward<Args>(args)...);
               ^
/Users/henryiii/git/software/histogram-python/extern/pybind11/include/pybind11/stl.h:352:33: note: in instantiation of function template
      specialization 'pybind11::detail::visit_helper<variant>::call<pybind11::detail::variant_caster_visitor,
      boost::histogram::axis::variant<boost::histogram::axis::regular<double, boost::use_default, boost::use_default, boost::use_default>,
      boost::histogram::axis::regular<double, boost::use_default, boost::use_default, boost::histogram::axis::option::bitset<0> >,
      boost::histogram::axis::regular<double, boost::histogram::axis::transform::id, boost::use_default,
      boost::histogram::axis::option::bitset<6> >, boost::histogram::axis::regular<double, boost::histogram::axis::transform::log,
      boost::use_default, boost::use_default>, boost::histogram::axis::regular<double, boost::histogram::axis::transform::pow,
      boost::use_default, boost::use_default>, boost::histogram::axis::regular<double, boost::histogram::axis::transform::sqrt,
      boost::use_default, boost::use_default>, boost::histogram::axis::variable<double, boost::use_default, boost::use_default,
      std::__1::allocator<double> > > >' requested here
        return visit_helper<V>::call(variant_caster_visitor{policy, parent},
                                ^
/Users/henryiii/git/software/histogram-python/extern/pybind11/include/pybind11/pybind11.h:154:39: note: in instantiation of function template
      specialization 'pybind11::detail::variant_caster<boost::histogram::axis::variant<boost::histogram::axis::regular<double,
      boost::use_default, boost::use_default, boost::use_default>, boost::histogram::axis::regular<double, boost::use_default,
      boost::use_default, boost::histogram::axis::option::bitset<0> >, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::id, boost::use_default, boost::histogram::axis::option::bitset<6> >,
      boost::histogram::axis::regular<double, boost::histogram::axis::transform::log, boost::use_default, boost::use_default>,
      boost::histogram::axis::regular<double, boost::histogram::axis::transform::pow, boost::use_default, boost::use_default>,
      boost::histogram::axis::regular<double, boost::histogram::axis::transform::sqrt, boost::use_default, boost::use_default>,
      boost::histogram::axis::variable<double, boost::use_default, boost::use_default, std::__1::allocator<double> > >
      >::cast<boost::histogram::axis::variant<boost::histogram::axis::regular<double, boost::use_default, boost::use_default,
      boost::use_default>, boost::histogram::axis::regular<double, boost::use_default, boost::use_default,
      boost::histogram::axis::option::bitset<0> >, boost::histogram::axis::regular<double, boost::histogram::axis::transform::id,
      boost::use_default, boost::histogram::axis::option::bitset<6> >, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::log, boost::use_default, boost::use_default>, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::pow, boost::use_default, boost::use_default>, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::sqrt, boost::use_default, boost::use_default>, boost::histogram::axis::variable<double,
      boost::use_default, boost::use_default, std::__1::allocator<double> > > >' requested here
            handle result = cast_out::cast(
                                      ^
/Users/henryiii/git/software/histogram-python/extern/pybind11/include/pybind11/pybind11.h:65:9: note: in instantiation of function template
      specialization 'pybind11::cpp_function::initialize<(lambda at
      /Users/henryiii/git/software/histogram-python/src/histogram/histogram.cpp:121:9),
      boost::histogram::axis::variant<boost::histogram::axis::regular<double, boost::use_default, boost::use_default, boost::use_default>,
      boost::histogram::axis::regular<double, boost::use_default, boost::use_default, boost::histogram::axis::option::bitset<0> >,
      boost::histogram::axis::regular<double, boost::histogram::axis::transform::id, boost::use_default,
      boost::histogram::axis::option::bitset<6> >, boost::histogram::axis::regular<double, boost::histogram::axis::transform::log,
      boost::use_default, boost::use_default>, boost::histogram::axis::regular<double, boost::histogram::axis::transform::pow,
      boost::use_default, boost::use_default>, boost::histogram::axis::regular<double, boost::histogram::axis::transform::sqrt,
      boost::use_default, boost::use_default>, boost::histogram::axis::variable<double, boost::use_default, boost::use_default,
      std::__1::allocator<double> > >,
      boost::histogram::histogram<std::__1::vector<boost::histogram::axis::variant<boost::histogram::axis::regular<double, boost::use_default,
      boost::use_default, boost::use_default>, boost::histogram::axis::regular<double, boost::use_default, boost::use_default,
      boost::histogram::axis::option::bitset<0> >, boost::histogram::axis::regular<double, boost::histogram::axis::transform::id,
      boost::use_default, boost::histogram::axis::option::bitset<6> >, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::log, boost::use_default, boost::use_default>, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::pow, boost::use_default, boost::use_default>, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::sqrt, boost::use_default, boost::use_default>, boost::histogram::axis::variable<double,
      boost::use_default, boost::use_default, std::__1::allocator<double> > >,
      std::__1::allocator<boost::histogram::axis::variant<boost::histogram::axis::regular<double, boost::use_default, boost::use_default,
      boost::use_default>, boost::histogram::axis::regular<double, boost::use_default, boost::use_default,
      boost::histogram::axis::option::bitset<0> >, boost::histogram::axis::regular<double, boost::histogram::axis::transform::id,
      boost::use_default, boost::histogram::axis::option::bitset<6> >, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::log, boost::use_default, boost::use_default>, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::pow, boost::use_default, boost::use_default>, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::sqrt, boost::use_default, boost::use_default>, boost::histogram::axis::variable<double,
      boost::use_default, boost::use_default, std::__1::allocator<double> > > > >, boost::histogram::storage_adaptor<std::__1::vector<unsigned
      long long, std::__1::allocator<unsigned long long> > > > &, unsigned int, pybind11::name, pybind11::is_method, pybind11::sibling, char
      [33]>' requested here
        initialize(std::forward<Func>(f),
        ^
/Users/henryiii/git/software/histogram-python/extern/pybind11/include/pybind11/pybind11.h:1085:22: note: in instantiation of function template
      specialization 'pybind11::cpp_function::cpp_function<(lambda at
      /Users/henryiii/git/software/histogram-python/src/histogram/histogram.cpp:121:9), pybind11::name, pybind11::is_method, pybind11::sibling,
      char [33], void>' requested here
        cpp_function cf(method_adaptor<type>(std::forward<Func>(f)), name(name_), is_method(*this),
                     ^
/Users/henryiii/git/software/histogram-python/src/histogram/histogram.cpp:120:6: note: in instantiation of function template specialization
      'pybind11::class_<boost::histogram::histogram<std::__1::vector<boost::histogram::axis::variant<boost::histogram::axis::regular<double,
      boost::use_default, boost::use_default, boost::use_default>, boost::histogram::axis::regular<double, boost::use_default,
      boost::use_default, boost::histogram::axis::option::bitset<0> >, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::id, boost::use_default, boost::histogram::axis::option::bitset<6> >,
      boost::histogram::axis::regular<double, boost::histogram::axis::transform::log, boost::use_default, boost::use_default>,
      boost::histogram::axis::regular<double, boost::histogram::axis::transform::pow, boost::use_default, boost::use_default>,
      boost::histogram::axis::regular<double, boost::histogram::axis::transform::sqrt, boost::use_default, boost::use_default>,
      boost::histogram::axis::variable<double, boost::use_default, boost::use_default, std::__1::allocator<double> > >,
      std::__1::allocator<boost::histogram::axis::variant<boost::histogram::axis::regular<double, boost::use_default, boost::use_default,
      boost::use_default>, boost::histogram::axis::regular<double, boost::use_default, boost::use_default,
      boost::histogram::axis::option::bitset<0> >, boost::histogram::axis::regular<double, boost::histogram::axis::transform::id,
      boost::use_default, boost::histogram::axis::option::bitset<6> >, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::log, boost::use_default, boost::use_default>, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::pow, boost::use_default, boost::use_default>, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::sqrt, boost::use_default, boost::use_default>, boost::histogram::axis::variable<double,
      boost::use_default, boost::use_default, std::__1::allocator<double> > > > >, boost::histogram::storage_adaptor<std::__1::vector<unsigned
      long long, std::__1::allocator<unsigned long long> > > >>::def<(lambda at
      /Users/henryiii/git/software/histogram-python/src/histogram/histogram.cpp:121:9), char [33]>' requested here
    .def("axis",
     ^
/Users/henryiii/git/software/histogram-python/src/histogram/histogram.cpp:167:5: note: in instantiation of function template specialization
      'register_histogram_by_type<std::__1::vector<boost::histogram::axis::variant<boost::histogram::axis::regular<double, boost::use_default,
      boost::use_default, boost::use_default>, boost::histogram::axis::regular<double, boost::use_default, boost::use_default,
      boost::histogram::axis::option::bitset<0> >, boost::histogram::axis::regular<double, boost::histogram::axis::transform::id,
      boost::use_default, boost::histogram::axis::option::bitset<6> >, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::log, boost::use_default, boost::use_default>, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::pow, boost::use_default, boost::use_default>, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::sqrt, boost::use_default, boost::use_default>, boost::histogram::axis::variable<double,
      boost::use_default, boost::use_default, std::__1::allocator<double> > >,
      std::__1::allocator<boost::histogram::axis::variant<boost::histogram::axis::regular<double, boost::use_default, boost::use_default,
      boost::use_default>, boost::histogram::axis::regular<double, boost::use_default, boost::use_default,
      boost::histogram::axis::option::bitset<0> >, boost::histogram::axis::regular<double, boost::histogram::axis::transform::id,
      boost::use_default, boost::histogram::axis::option::bitset<6> >, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::log, boost::use_default, boost::use_default>, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::pow, boost::use_default, boost::use_default>, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::sqrt, boost::use_default, boost::use_default>, boost::histogram::axis::variable<double,
      boost::use_default, boost::use_default, std::__1::allocator<double> > > > >, boost::histogram::storage_adaptor<std::__1::vector<unsigned
      long long, std::__1::allocator<unsigned long long> > > >' requested here
    register_histogram_by_type<axes::any, vector_int_storage>(hist,
    ^
/Users/henryiii/git/software/histogram-python/extern/variant/include/boost/variant/variant.hpp:1544:10: note: candidate function [with T =
      boost::histogram::axis::variant<boost::histogram::axis::regular<double, boost::use_default, boost::use_default, boost::use_default>,
      boost::histogram::axis::regular<double, boost::use_default, boost::use_default, boost::histogram::axis::option::bitset<0> >,
      boost::histogram::axis::regular<double, boost::histogram::axis::transform::id, boost::use_default,
      boost::histogram::axis::option::bitset<6> >, boost::histogram::axis::regular<double, boost::histogram::axis::transform::log,
      boost::use_default, boost::use_default>, boost::histogram::axis::regular<double, boost::histogram::axis::transform::pow,
      boost::use_default, boost::use_default>, boost::histogram::axis::regular<double, boost::histogram::axis::transform::sqrt,
      boost::use_default, boost::use_default>, boost::histogram::axis::variable<double, boost::use_default, boost::use_default,
      std::__1::allocator<double> > >]
    void convert_construct(
         ^
/Users/henryiii/git/software/histogram-python/extern/variant/include/boost/variant/variant.hpp:1673:15: note: candidate function [with U0 =
      boost::histogram::axis::regular<double, boost::use_default, boost::use_default, boost::use_default>, UN =
      <boost::histogram::axis::regular<double, boost::use_default, boost::use_default, boost::histogram::axis::option::bitset<0> >,
      boost::histogram::axis::regular<double, boost::histogram::axis::transform::id, boost::use_default,
      boost::histogram::axis::option::bitset<6> >, boost::histogram::axis::regular<double, boost::histogram::axis::transform::log,
      boost::use_default, boost::use_default>, boost::histogram::axis::regular<double, boost::histogram::axis::transform::pow,
      boost::use_default, boost::use_default>, boost::histogram::axis::regular<double, boost::histogram::axis::transform::sqrt,
      boost::use_default, boost::use_default>, boost::histogram::axis::variable<double, boost::use_default, boost::use_default,
      std::__1::allocator<double> >>]
    > >::type convert_construct(
              ^
/Users/henryiii/git/software/histogram-python/extern/variant/include/boost/variant/variant.hpp:1685:15: note: candidate function [with U0 =
      boost::histogram::axis::regular<double, boost::use_default, boost::use_default, boost::use_default>, UN =
      <boost::histogram::axis::regular<double, boost::use_default, boost::use_default, boost::histogram::axis::option::bitset<0> >,
      boost::histogram::axis::regular<double, boost::histogram::axis::transform::id, boost::use_default,
      boost::histogram::axis::option::bitset<6> >, boost::histogram::axis::regular<double, boost::histogram::axis::transform::log,
      boost::use_default, boost::use_default>, boost::histogram::axis::regular<double, boost::histogram::axis::transform::pow,
      boost::use_default, boost::use_default>, boost::histogram::axis::regular<double, boost::histogram::axis::transform::sqrt,
      boost::use_default, boost::use_default>, boost::histogram::axis::variable<double, boost::use_default, boost::use_default,
      std::__1::allocator<double> >>]
    > >::type convert_construct(
              ^
/Users/henryiii/git/software/histogram-python/extern/variant/include/boost/variant/variant.hpp:1698:15: note: candidate function [with U0 =
      boost::histogram::axis::regular<double, boost::use_default, boost::use_default, boost::use_default>, UN =
      <boost::histogram::axis::regular<double, boost::use_default, boost::use_default, boost::histogram::axis::option::bitset<0> >,
      boost::histogram::axis::regular<double, boost::histogram::axis::transform::id, boost::use_default,
      boost::histogram::axis::option::bitset<6> >, boost::histogram::axis::regular<double, boost::histogram::axis::transform::log,
      boost::use_default, boost::use_default>, boost::histogram::axis::regular<double, boost::histogram::axis::transform::pow,
      boost::use_default, boost::use_default>, boost::histogram::axis::regular<double, boost::histogram::axis::transform::sqrt,
      boost::use_default, boost::use_default>, boost::histogram::axis::variable<double, boost::use_default, boost::use_default,
      std::__1::allocator<double> >>] not viable: no known conversion from
      'boost::histogram::axis::variant<boost::histogram::axis::regular<double, boost::use_default, boost::use_default, boost::use_default>,
      boost::histogram::axis::regular<double, boost::use_default, boost::use_default, boost::histogram::axis::option::bitset<0> >,
      boost::histogram::axis::regular<double, boost::histogram::axis::transform::id, boost::use_default,
      boost::histogram::axis::option::bitset<6> >, boost::histogram::axis::regular<double, boost::histogram::axis::transform::log,
      boost::use_default, boost::use_default>, boost::histogram::axis::regular<double, boost::histogram::axis::transform::pow,
      boost::use_default, boost::use_default>, boost::histogram::axis::regular<double, boost::histogram::axis::transform::sqrt,
      boost::use_default, boost::use_default>, boost::histogram::axis::variable<double, boost::use_default, boost::use_default,
      std::__1::allocator<double> > >' to 'boost::variant<regular<double, use_default, use_default, use_default>, regular<double, use_default,
      use_default, bitset<0> >, regular<double, id, use_default, bitset<6> >, regular<double, log, use_default, use_default>, regular<double,
      pow, use_default, use_default>, regular<double, sqrt, use_default, use_default>, variable<double, use_default, use_default,
      allocator<double> > > &&' for 1st argument
    > >::type convert_construct(
              ^
/Users/henryiii/git/software/histogram-python/extern/variant/include/boost/variant/variant.hpp:1565:31: note: candidate template ignored:
      disabled by 'enable_if' [with T = boost::histogram::axis::variant<boost::histogram::axis::regular<double, boost::use_default,
      boost::use_default, boost::use_default>, boost::histogram::axis::regular<double, boost::use_default, boost::use_default,
      boost::histogram::axis::option::bitset<0> >, boost::histogram::axis::regular<double, boost::histogram::axis::transform::id,
      boost::use_default, boost::histogram::axis::option::bitset<6> >, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::log, boost::use_default, boost::use_default>, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::pow, boost::use_default, boost::use_default>, boost::histogram::axis::regular<double,
      boost::histogram::axis::transform::sqrt, boost::use_default, boost::use_default>, boost::histogram::axis::variable<double,
      boost::use_default, boost::use_default, std::__1::allocator<double> > > &]
    typename boost::enable_if<boost::is_rvalue_reference<T&&> >::type convert_construct(
                              ^
/Users/henryiii/git/software/histogram-python/extern/variant/include/boost/variant/variant.hpp:1586:10: note: candidate function template not
      viable: requires 3 arguments, but 2 were provided
    void convert_construct(
         ^
/Users/henryiii/git/software/histogram-python/extern/variant/include/boost/variant/variant.hpp:1600:77: note: candidate function template not
      viable: requires 3 arguments, but 2 were provided
    typename boost::enable_if<boost::is_rvalue_reference<Variant&&> >::type convert_construct(
                                                                            ^
1 error generated.
```

</details>

### CODE REVIEW

**Comment by henryiii** [comment]
@HDembinski , could you take a look and see why adding `axis::variable` breaks the variant? The following code works inside Boost::Histogram's tests:

```cpp
   // testing mixing axis types
   {

     // These match the Python names
     using regular = axis::regular<>;
     using regular_noflow = axis::regular<double, use_default, use_default, axis::option::none_t>;
     using circular = axis::circular<>;
     using regular_log = axis::regular<double, axis::transform::log>;
     using regular_sqrt = axis::regular<double, axis::transform::sqrt>;
     using regular_pow = axis::regular<double, axis::transform::pow>;
     using variable = axis::variable<double>;

     auto a = axis::variant<
             regular,
             regular_noflow,
             circular,
             regular_log,
             regular_pow,
             regular_sqrt,
             variable
         >{
         axis::regular<>(5, 1., 6.)};

     axis::visit([](auto&& arg){std::cout << arg;}, a);

   }
```

So maybe it's due to the way Pybind11 is visiting?

**Comment by henryiii** [comment]
I think this is suspect: If I just have a variable axis in the variant, the error message is simpler and I see this suspicious line:

```cpp
/Users/henryiii/git/software/histogram-python/extern/variant/include/boost/variant/variant.hpp:1698:15: note: candidate function [with U0 =
      boost::histogram::axis::variable<double, boost::use_default, boost::use_default, std::__1::allocator<double> >, UN = <>] not viable: no known conversion from
      'boost::histogram::axis::variant<boost::histogram::axis::variable<double, boost::use_default, boost::use_default, std::__1::allocator<double> > >' to
      'boost::variant<variable<double, use_default, use_default, allocator<double> > > &&' for 1st argument
    > >::type convert_construct(
```

**Comment by henryiii** [comment]
Big step forward: removing `axis(i)` allows this to compile. So the visitation that is causing the error is only when wrapping axis. This works if added to Boost::Histogram's tests, so it has something to do with being the right value type to trigger boost::variant's conversion that has a hardcoded boost::variant in it.

**Comment by HDembinski** [comment]
I just checked in Boost::Histogram that `axis(i)` works on a `histogram<std::vector<axis::variant<...>, ...>`. `axis::variant` inherits from `boost::variant`, so the former is implicitly convertible into the latter. However, the target type here is a rvalue reference. This may be the problem.

**Comment by henryiii** [comment]
> I just checked in Boost::Histogram that axis(i) works on a...

Sorry for the duplicated work, that is what I meant that I tried when I wrote: "This works if added to Boost::Histogram's tests".

**Comment by HDembinski** [comment]
> Sorry for the duplicated work, that is what I meant that I tried when I wrote: "This works if added to Boost::Histogram's tests".

No, that's ok, I understood you, but wanted to check for myself. I am working on a fix inside Boost::Histogram which will resolve this ambiguity, but it needs more time.

**Comment by henryiii** [comment]
> I am working on a fix inside Boost::Histogram which will resolve this ambiguity

Perfect. We will hold off on axis::variable until that's ready. I have axis::integer ready so that will probably go in after the CI merge.

**Comment by HDembinski** [comment]
Could you please try again with this branch of boost::histogram https://github.com/HDembinski/histogram/tree/variable_axis_issue ?

**Comment by HDembinski** [comment]
It should be working now.

**Comment by HDembinski** [comment]
The CI tests are ok on 
https://github.com/HDembinski/histogram/tree/variable_axis_issue,
 so I am going to merge this into `develop` as soon as you give the green light

**Comment by henryiii** [comment]
💚 (the branch builds perfectly with this change!)

**Comment by HDembinski** [comment]
🎉  :)

**Pull request merged**
