### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by eduardo-rodrigues**

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
@henryiii, true that the template provided by Azure is rather simple and you would need to tailor the YAML file to your specific needs. But why do you not want to start from this and rather closed the PR?

Can I be of any help?

I hope you got the correct rights in Azure. I believe I did things right last night.

**Comment by henryiii** [comment]
I think you did set the permissions correctly, though you also have correctly set up the CI so there wasn't anything else to do. I already had a PR based on Particle and CLI11's Azure setup (#5), and am just continuing on that.

**Comment by eduardo-rodrigues** [comment]
OK, all good so long as the CI gets sorted ;-)-

**Comment by henryiii** [comment]
It is about to, should merge in ~5 minutes. :)

**Pull request closed without merging**
