### PR TITLE
Fill

### PR DESCRIPTION
**Pull request by HDembinski**
This adds an alternative fill strategy. This can be easily extended to support weights, but I would like to see how it fares in benchmarks first before we proceed.

### CODE REVIEW

**Comment by HDembinski** [comment]
This is the idea I was talking about. This fill version may be faster for general histograms. I currently cannot test it, because I had to a massive rebase and pytest fails on the new develop branch. But it was working before.

**Comment by HDembinski** [comment]
I am not sure why the tests didn't trigger, I can see no reason why they shouldn't.

**Comment by HDembinski** [comment]
Sorry, not ready for review yet, I just noticed...

**Comment by henryiii** [comment]
Next push here will build on Azure.

**Comment by henryiii** [comment]
Ping me when ready to benchmark.

**Comment by HDembinski** [comment]
All tests pass on my machine now, you can try the benchmark.

**Comment by HDembinski** [comment]
What's there:
- generic fill implementation for ND histograms without the code bloat of the previous solution
- fast 1D implementation, which should be as fast for static histograms and dynamic histograms, making specializations for static histograms obsolete

Weights and samples:
The ND fill implementation has support for weights and samples, but this is untested. The 1D fill implementation does not have it yet, but it should be clear how to add it after a careful reading of the code. I am running out of time to work on this.

**Comment by HDembinski** [comment]
Code is now included in boost::histogram

**Pull request closed without merging**
