### PR TITLE
Update externals

### PR DESCRIPTION
**Pull request by HDembinski**
update boost stuff to 1.71.0 and boost::histogram to develop

### CODE REVIEW

**Comment by henryiii** [comment]
Every Sunday, Azure checks out all dev branches and runs a test to see if we are still compatible with head. Looks like this problem started happening just this week. <https://dev.azure.com/scikit-hep/boost-histogram/_build?definitionId=7>

I'll look into it in the next day or two.

**Comment by HDembinski** [comment]
I already worked out a fix. The tests discovered a bug in Boost::Histogram.

**Comment by HDembinski** [comment]
> Every Sunday, Azure checks out all dev branches and runs a test to see if we are still compatible with head.

I think this is not a good idea except maybe for Boost::Histogram. You don't want to live at head for other externals.

**Comment by henryiii** [comment]
Boost Histogram requires the latest head on the other externals; at least it required >1.69 and >1.70. I don't plan to actually update the internal versions of the other externals to head unless it's needed - it's just for the check.

**Pull request merged**
