### PR TITLE
Adding shortcut for regular and variable axes

### PR DESCRIPTION
**Pull request by henryiii**
This makes the following equivalent:

```python
bh.histogram((10, 0, 1, "x"), [0, .5, .6, .9, 1.2])
```

```python
bh.histogram(bh.axis.regular(10, 0, 1, "x"), bh.axis.variable([0, .5, .6, .9, 1.2]))
```

A final string can be detected and used as metadata.

### CODE REVIEW

**Comment by HDembinski** [comment]
I am not happy with this patch. How do you handle the ambiguous case? `bh.histogram((10, 20, 30))`?

**Comment by HDembinski** [comment]
Does this generate a regular axis or a variable axis? Do you want to treat tuples differently from lists?

**Comment by henryiii** [comment]
Yes, tuples are a shortcut for regular axes, and lists are shortcuts for variable axes. No other types are accepted. `histogram((1,2,3,4,5,6))` is an error. If you want to to make a variable axis with a preexisting value, you can use `boost.histogram.axis.variable`. `histogram` itself is just a shortcut after all.

**Comment by henryiii** [comment]
Discussion can still be open; I needed the patch for the readme updates.

**Comment by henryiii** [comment]
The tuple for a regular axis is very handy, and is fantastic for power users to quickly throw together a histogram for testing or quick uses. It's probably not nearly as common to make a variable binned axis, and that's already longer and more typing, so I could be convinced to drop that.

**Comment by HDembinski** [comment]
I guess it is not surprising by now that I find this a terrible idea.

**Comment by HDembinski** [comment]
Python treats all sequence types the same, so you cannot give some sequence type a special meaning. This is going to cause bugs. Less so when you use it directly, but code evolves, stuff you wrote in main gets put in functions, then those functions are refactored. At some point, someone forgot that tuples are handled differently from lists. It is very very unpythonic and error-prone.

**Comment by HDembinski** [comment]
Also, I don't see the benefit. You can already have shorthand.
```
from boost.histogram.axis import regular as r, variable as v

histogram(r(10, 20, 30), v(1, 2, 3))
```

**Comment by HDembinski** [comment]
If `axis.variable` doesn't  accept `*args`, perhaps that's a better direction to improve.

**Comment by henryiii** [comment]
You just wrote 98 characters instead of 34 or 61. And you skipped importing histogram. How is that a shortcut? And now you have used r and v, two of the most common characters to use for radius and values.

Python is *not* C++. It is meant to be used on the command line. The main Python libraries provide ways to do things quickly. For example, `numpy.array` does *not* accept arbitrary iterables; only lists and tuples. You have to use `numpy.fromiter()`. This is because they needed a quick, no mess way to make multiple dimensional arrays. Unless people live and breath histograms, they will want a simple way to make histograms. And if they do live-and-breath histograms, they won't want to type a ton of characters each time.

Making a simple histogram should not require a series of imports. If people can do:

```python
import numpy as np
np.histogram2d(data, bins=(10,10), range=((-1,1), (-1,1)))
```

vs:

```python
import boost.histogram as bh
hist = bh.histogram(bh.axis.regular(10, -1, 1), bh.axis.regular(10, -1, 1))
hist.fill(data)
```

But, compare:

```python
import boost.histogram as bh
bh.histogram((10, -1, 1), (10, -1, 1))
hist.fill(data)
```

**Comment by henryiii** [comment]
If someone doesn't want the shortcut, they don't have to use it. `histogram` is already just a shortcut for making histograms. If you refactor this at some point, you should use `axis.variable`. However, since it might be controversial, I've dropped lists for now, maybe we can add it back later.

**Comment by HDembinski** [comment]
This is again about "making interfaces hard to use incorrectly". And about writing Pythonic libraries. Giving lists and tuples different meaning is not Pythonic, as I have explained before in another context.

**Comment by HDembinski** [comment]
> You just wrote 98 characters instead of 34 or 61. And you skipped importing histogram. How is that a shortcut? And now you have used r and v, two of the most common characters to use for radius and values.

You write the imports only once at the top of your notebook, you don't need shorthand there.

> Python is not C++. It is meant to be used on the command line.

I am well aware of this, but you cannot drop safety and core Pythonic principles to get short syntax. It is a matter of priorities. I think you must agree that "making interfaces safe to use" is more important than anything else. And if you do, then you accept my counter-argument to your proposal instead of reiterating your position, which I already am well aware of. Just reinforcing what you want doesn't invalidate my counter-argument.

The problem is not I don't see the value in what you want. The problem is that you disregard my counter-argument, which you cannot, if we have the same priorities.

**Comment by HDembinski** [comment]
```c++
import boost.histogram as bh
from bh.axis imort regular as r, variable as v

bh.histogram(r(10, -1, 1), v(1, 2, 3))
hist.fill(data)
```
Is also nice and short.

Besides, you are inconsistent with your position. You treat characters like the cost money, but you insist on five superfluous characters `.fill` which are completely avoidable.

**Comment by HDembinski** [comment]
And you complaint that the `__call__` operator is not returning anything is not true anymore. In Boost::Histogram it returns an iterator to the current cell, similar to ROOT.

**Comment by henryiii** [comment]
Using `__call__` hides the fact it's a histogram when you duck-type. If I run:

    h(2)

It's not clear what h is or what it does. However, if I run

    h.fill(2)

It's quite clear that I expect it to be a histogram. You didn't want `h[x]` to be confusable with arrays. It's also clear that h is now probably changed.

**Comment by henryiii** [comment]
I want it to be easy to use interactively. Typing a bit more interactively is okay, your thought flow is still going. If you have to type a bunch of stuff just to set up your environment, then that's a problem. It's why pylab exists, and `from numpy import *`, and other atrocities. It's why numpy and pandas both provide methods to do things `x.sum()` instead of requiring users to `np.sum(x)`; you don't have to set that up if you already have an array and it's easy to find by pressing "tab".

**Comment by henryiii** [comment]
What about this:

```python
from boost.histogram import histogram
from bh.axis import regular as r, variable as v

# stuff

theta = 1.2
r = 2.3

# more stuff ...

histogram = histogram(r(10, -1, 1), v(1, 2, 3))
histogram(r, theta)
```

Do you see the inherent dangers here? I see at least 2. What's worse, the error messages might not be that helpful.

None of this would be a problem in a strongly-typed language like C++. You would not be able to override r, and histogram would have a clearly defined type. (Though overusing auto can be an issue).

**Comment by henryiii** [comment]
> ```python
> import boost.histogram as bh
> from bh.axis imort regular as r, variable as v
> ```

This is not valid python. You can't import from an object. It has to be a fully qualified name.

```python
from boost.histogram.axis imort regular as r, variable as v
```

**Comment by HDembinski** [comment]
> I want it to be easy to use interactively. Typing a bit more interactively is okay, your thought flow is still going. If you have to type a bunch of stuff just to set up your environment, then that's a problem. It's why pylab exists, and `from numpy import *`, and other atrocities. It's why numpy and pandas both provide methods to do things `x.sum()` instead of requiring users to `np.sum(x)`; you don't have to set that up if you already have an array and it's easy to find by pressing "tab".

Again, I am aware of all that. Our conflict is not about me not understanding you. So repeating your position is not helping.

**Comment by HDembinski** [comment]
```
from boost.histogram import histogram
from bh.axis import regular as r, variable as v

# stuff

theta = 1.2
r = 2.3

# more stuff ...

histogram = histogram(r(10, -1, 1), v(1, 2, 3))
histogram(r, theta)
```

The `histogram = histogram(...)` is unrelated to our discussion. And the mistake with `r` will give you a quite useful error message ("no call operator for float" or something like that)

**Comment by HDembinski** [comment]
Using short names is always a danger, fair enough, but what you are suggesting is worse than this.

**Comment by henryiii** [comment]
You just brought `__call__` into our discussion, this is a problem with `__call__` vs. `fill`.

**Comment by HDembinski** [comment]
```
histogram = histogram(r(10, -1, 1), v(1, 2, 3))
histogram(r, theta)
```
does the same as 
```
histogram = histogram(r(10, -1, 1), v(1, 2, 3))
histogram.fill(r, theta)
```
so how is `.fill` helping here?

**Comment by HDembinski** [comment]
Both work as expected, you only get an error when you try to make another histogram afterwards. I don't see how this is related to our discussion.

**Comment by henryiii** [comment]
Are you objecting to having both shortcuts, or just the one? (tuple for regular axis). I have a PR to remove the list <-> variable axis. Then tuples would be a fast way to build regular axes, since that's what most analysts would want fast access to, and variable axes would have to be explicit.

**Comment by HDembinski** [comment]
About regular(...) vs `(...)`, here you are willing to sacrifice safety at the gain of a few characters. This choice makes me think that you don't really care about safety or readability. But when it is about `.fill`, you take the opposite position. Using `.fill` is not safer than `__call__`, it is just a bit more readable. But you don't care about readability, since you want to use `(...)` instead of `regular(...)`. That's inconsistent.

**Comment by HDembinski** [comment]
The point is, I am ok with `.fill` instead of `__call__`, although I don't personally like it and you are introducing a difference between boost-histogram and boost::histogram.

**Comment by henryiii** [comment]
If we don't have the list syntax, what safety am I sacrificing?

**Comment by HDembinski** [comment]
If you drop the list syntax, the conflict is solved. If every sequence is interpreted as a regular axis, that's ok. I still don't like it and I ask you do introduce this to hist and not boost-histogram, but there is not safety concern then.

**Comment by HDembinski** [comment]
It is still bad design, because the regular axis gets special treatment.

**Comment by henryiii** [comment]
The regular axis is the most common type of histogram, especially for quick use cases. It also gets special treatment in other ways (if you only have regular axes, filling is faster). It's what people are going to be familiar with coming into our package. Compare other libraries:

```python
# Numpy
np.histogram2d(xvalues, yvalues, (10, 10), ((-1, 1), (-1, 1)))
# ROOT
ROOT.TH2D("title", "title", 10, -1, 1, 10, -1, 1)
```

to

```python
bh.histogram((10, -1, 1), (10, -1, 1))
```

or

```python
histogram(bh.axis.regular(10, -1, 1), bh.axis.regular(10, -1, 1))
```

**Comment by henryiii** [comment]
Note that numpy gives special treatment to lists and tuples inside the array function. That's because they are making it reasonably easy to make arrays, and keeping the entry barrier low. Try `np.array(i for i in range(10))`; it does not make an array of 10 values. They explicitly check for tuples and arrays (and the `range` object now, apparently) so that it's easy to construct multidimensional arrays. `array([[1]])` should make a length 1 1D array with a python list in it, but it doesn't, because it's more practical to expand these. `np.fromiter` is provided.

**Pull request merged**
