### PR TITLE
Python-ready repr

### PR DESCRIPTION
**Pull request by henryiii**
Fixes part of #90; the repr's are now stable and provide Python-ready syntax. This does not add a quick way to preview the contents of histograms or the bin edges, might be in a later PR.

### CODE REVIEW

**Comment by henryiii** [comment]
(I forgot to run the python formatter; this is why I need a formatting check!)

**Comment by henryiii** [comment]
I'm going to merge this soon, but @HDembinski please let me know if you have any comments, we can always change it. I can't work on #104 until this is merged.

**Comment by henryiii** [comment]
Always == before release, anyway. And, in this case, repr's are not guarantied to be steady between releases (as LHCb found out, they were depending on the repr of an float, which changed in Python 2.6 or 2.7)

**Comment by HDembinski** [comment]
I would have implemented the `__repr__` in Python, but the repr string for the axes looks good and it `eval`s back to the original class, which is nice. For the histogram, we can't have it `eval` back, so we are more free in the format.

**Pull request merged**
