### PR TITLE
feat: add boilerplate sub implementation

### PR DESCRIPTION
**Pull request by amangoel185**
Basic implementation for #632.

TODO:

- [x] Add test for scalar
- [x] Add test for array
- [x] Add test for Histogram (expected to throw unless Boost.Histogram adds or supports sub)
- [x] Add test for int storage < 0 after subtraction (unsigned currently) - should throw, convert to double, or storages should be signed.

### CODE REVIEW

**Comment by amangoel185** [comment]
We need to implement `__isub__` but it has to be in accordance with Boost.Histogram

**Comment by henryiii** [comment]
@HDembinski Question for you: should Hist - Hist be supported? I'd only want to support it in boost-histogram if Boost.Histogram supports it, or you have a good reason to support it only in boost-histogram. It's not hard to be explicit - `h1 - h2.view(flow=True)` for example should do it since subtracting an array should be supported.

Also, maybe we should switch to using signed storage so that subtraction (and negative weights?) work without having to change storages or throw an error. Technically, NumPy uses signed ints, IIRC.

**Comment by HDembinski** [comment]
I think Hist should support what boost-histogram supports. The added benefit is that hist - hist can check whether this actually makes sense, it should fail if the axes are not the same.

**Comment by henryiii** [comment]
@HDembinski Sorry, my notation was sloppy. I wasn't suggesting Hist and boost-histogram diverge, I was just asking if a histogram histogram subtraction, `bh.Histogram(...) - bh.Histogram(...)`, should be supported. I was under the impression Boost.Histogram didn't currently support negating and subtracting histograms, but looking at the code, it seems to just fine. So we should add this in boost-histogram!

**Comment by henryiii** [comment]
Okay, needs tests now. @amangoel185 can you look into adding tests as outlined above? Or I might be able to later.

**Comment by henryiii** [comment]
Weighted and AtomicInt64 histograms do not support subtraction, so they don't support subtraction here either.

**Comment by henryiii** [comment]
@all-contributors please add @amangoel185 for code

**Comment by henryiii** [comment]
After this goes in, I think we should cut a patch release - there have been a few nice fixes, and Python 3.10 support needs to ship.

**Pull request merged**
