### PR TITLE
Atomic and threaded fills

### PR DESCRIPTION
**Pull request by henryiii**
This adds perf tools and experimental atomic fills and threaded copy fills. I will probably drop the tuple overloads, since they don't provide much and currently disallow projection.

# Current results:

These results are comparable to [my histogram speed blog post](https://iscinumpy.gitlab.io/post/histogram-speeds-in-python/) (though in this case I'm using 64 bit doubles instead of 32 bit floats for the source).

Time is time per run (total time / 10).

### 1D, 10 runs each

| Type  | Storage | Fill | Flow |    Time   | Speedup |
|-------|---------|------|------|-----------|---------|
| Numpy | uint64  |      |  no  |  149.4 ms |      1x |
|  Any  |   int   |      | yes  |    236 ms |   0.63x |
|  Any  |   int   |      |  no  |  228.6 ms |   0.65x |
|Regular|   int   |      | yes  |  86.23 ms |    1.7x |
|Regular|   int   |      |  no  |  82.03 ms |    1.8x |
|Regular| int 1D  |      | yes  |  87.24 ms |    1.7x |
|Regular| int 1D  |      |  no  |  82.68 ms |    1.8x |
|Regular|  aint   |      | yes  |  134.1 ms |    1.1x |
|Regular|  aint   |  1   | yes  |    132 ms |    1.1x |
|Regular|  aint   |  2   | yes  |  168.2 ms |   0.89x |
|Regular|  aint   |  4   | yes  |  143.6 ms |      1x |
|Regular|   int   |  1   | yes  |  84.75 ms |    1.8x |
|Regular|   int   |  2   | yes  |   51.6 ms |    2.9x |
|Regular|   int   |  4   | yes  |  42.39 ms |    3.5x |

### 2D, 10 runs each

| Type  | Storage | Fill | Flow |    Time   | Speedup |
|-------|---------|------|------|-----------|---------|
| Numpy | uint64  |      |  no  |  121.1 ms |      1x |
|  Any  |   int   |      | yes  |  37.12 ms |    3.3x |
|  Any  |   int   |      |  no  |  36.24 ms |    3.3x |
|Regular|   int   |      | yes  |   18.5 ms |    6.5x |
|Regular|   int   |      |  no  |  16.83 ms |    7.2x |
|Regular| int 2D  |      | yes  |   13.2 ms |    9.2x |
|Regular| int 2D  |      |  no  |  12.62 ms |    9.6x |
|Regular|  aint   |      | yes  |   20.3 ms |      6x |
|Regular|  aint   |  1   | yes  |  20.21 ms |      6x |
|Regular|  aint   |  2   | yes  |  14.17 ms |    8.5x |
|Regular|  aint   |  4   | yes  |  10.23 ms |     12x |
|Regular|   int   |  1   | yes  |  17.86 ms |    6.8x |
|Regular|   int   |  2   | yes  |   9.41 ms |     13x |
|Regular|   int   |  4   | yes  |  6.854 ms |     18x |

### 1D, 10 runs each

| Type  | Storage | Fill | Flow |    Time   | Speedup |
|-------|---------|------|------|-----------|---------|
| Numpy | uint64  |      |  no  |    121 ms |      1x |
|  Any  |   int   |      | yes  |  261.5 ms |   0.46x |
|  Any  |   int   |      |  no  |  259.3 ms |   0.47x |
|Regular|   int   |      | yes  |  142.2 ms |   0.85x |
|Regular|   int   |      |  no  |  144.5 ms |   0.84x |
|Regular| int 1D  |      | yes  |  144.7 ms |   0.84x |
|Regular| int 1D  |      |  no  |  138.9 ms |   0.87x |
|Regular|  aint   |      | yes  |  160.7 ms |   0.75x |
|Regular|  aint   |  1   | yes  |  319.1 ms |   0.38x |
|Regular|  aint   |  3   | yes  |  401.3 ms |    0.3x |
|Regular|  aint   |  6   | yes  |  392.4 ms |   0.31x |
|Regular|  aint   |  12  | yes  |  497.4 ms |   0.24x |
|Regular|  aint   |  24  | yes  |  346.6 ms |   0.35x |
|Regular|  aint   |  48  | yes  |  272.9 ms |   0.44x |
|Regular|   int   |  1   | yes  |  243.4 ms |    0.5x |
|Regular|   int   |  3   | yes  |  143.8 ms |   0.84x |
|Regular|   int   |  6   | yes  |  94.76 ms |    1.3x |
|Regular|   int   |  12  | yes  |  71.38 ms |    1.7x |
|Regular|   int   |  24  | yes  |  52.26 ms |    2.3x |
|Regular|   int   |  48  | yes  |  43.01 ms |    2.8x |

### 2D, 10 runs each

| Type  | Storage | Fill | Flow |    Time   | Speedup |
|-------|---------|------|------|-----------|---------|
| Numpy | uint64  |      |  no  |  87.27 ms |      1x |
|  Any  |   int   |      | yes  |  41.42 ms |    2.1x |
|  Any  |   int   |      |  no  |  40.38 ms |    2.2x |
|Regular|   int   |      | yes  |  21.67 ms |      4x |
|Regular|   int   |      |  no  |  21.64 ms |      4x |
|Regular| int 2D  |      | yes  |  21.22 ms |    4.1x |
|Regular| int 2D  |      |  no  |  20.47 ms |    4.3x |
|Regular|  aint   |      | yes  |  24.26 ms |    3.6x |
|Regular|  aint   |  1   | yes  |  38.61 ms |    2.3x |
|Regular|  aint   |  3   | yes  |  31.51 ms |    2.8x |
|Regular|  aint   |  6   | yes  |  19.89 ms |    4.4x |
|Regular|  aint   |  12  | yes  |   12.5 ms |      7x |
|Regular|  aint   |  24  | yes  |  9.556 ms |    9.1x |
|Regular|  aint   |  48  | yes  |  8.518 ms |     10x |
|Regular|   int   |  1   | yes  |   36.5 ms |    2.4x |
|Regular|   int   |  3   | yes  |  16.77 ms |    5.2x |
|Regular|   int   |  6   | yes  |  8.976 ms |    9.7x |
|Regular|   int   |  12  | yes  |  5.318 ms |     16x |
|Regular|   int   |  24  | yes  |  4.388 ms |     20x |
|Regular|   int   |  48  | yes  |  5.839 ms |     15x |

### 1D, 10 runs each

| Type  | Storage | Fill | Flow |    Time   | Speedup |
|-------|---------|------|------|-----------|---------|
| Numpy | uint64  |      |  no  |  716.9 ms |      1x |
|  Any  |   int   |      | yes  |   1418 ms |   0.51x |
|  Any  |   int   |      |  no  |   1410 ms |   0.51x |
|Regular|   int   |      | yes  |    824 ms |   0.87x |
|Regular|   int   |      |  no  |  798.9 ms |    0.9x |
|Regular| int 1D  |      | yes  |  792.1 ms |   0.91x |
|Regular| int 1D  |      |  no  |  777.4 ms |   0.92x |
|Regular|  aint   |      | yes  |  840.6 ms |   0.85x |
|Regular|  aint   |  1   | yes  |  871.7 ms |   0.82x |
|Regular|  aint   |  2   | yes  |  683.9 ms |      1x |
|Regular|  aint   |  4   | yes  |  437.1 ms |    1.6x |
|Regular|  aint   |  8   | yes  |    293 ms |    2.4x |
|Regular|  aint   |  16  | yes  |    241 ms |      3x |
|Regular|  aint   |  32  | yes  |  223.5 ms |    3.2x |
|Regular|  aint   |  64  | yes  |  198.8 ms |    3.6x |
|Regular|  aint   | 128  | yes  |  186.8 ms |    3.8x |
|Regular|  aint   | 256  | yes  |  195.2 ms |    3.7x |
|Regular|   int   |  1   | yes  |  796.9 ms |    0.9x |
|Regular|   int   |  2   | yes  |  430.6 ms |    1.7x |
|Regular|   int   |  4   | yes  |  247.6 ms |    2.9x |
|Regular|   int   |  8   | yes  |  157.2 ms |    4.6x |
|Regular|   int   |  16  | yes  |  112.9 ms |    6.3x |
|Regular|   int   |  32  | yes  |  93.12 ms |    7.7x |
|Regular|   int   |  64  | yes  |  88.77 ms |    8.1x |
|Regular|   int   | 128  | yes  |  98.08 ms |    7.3x |
|Regular|   int   | 256  | yes  |  112.2 ms |    6.4x |

### 2D, 10 runs each

| Type  | Storage | Fill | Flow |    Time   | Speedup |
|-------|---------|------|------|-----------|---------|
| Numpy | uint64  |      |  no  |  439.5 ms |      1x |
|  Any  |   int   |      | yes  |  250.6 ms |    1.8x |
|  Any  |   int   |      |  no  |  247.5 ms |    1.8x |
|Regular|   int   |      | yes  |  135.6 ms |    3.2x |
|Regular|   int   |      |  no  |  130.7 ms |    3.4x |
|Regular| int 2D  |      | yes  |  133.7 ms |    3.3x |
|Regular| int 2D  |      |  no  |  127.1 ms |    3.5x |
|Regular|  aint   |      | yes  |  139.4 ms |    3.2x |
|Regular|  aint   |  1   | yes  |  142.2 ms |    3.1x |
|Regular|  aint   |  2   | yes  |  92.65 ms |    4.7x |
|Regular|  aint   |  4   | yes  |  52.71 ms |    8.3x |
|Regular|  aint   |  8   | yes  |  28.98 ms |     15x |
|Regular|  aint   |  16  | yes  |  16.73 ms |     26x |
|Regular|  aint   |  32  | yes  |  12.05 ms |     36x |
|Regular|  aint   |  64  | yes  |   16.5 ms |     27x |
|Regular|  aint   | 128  | yes  |   30.7 ms |     14x |
|Regular|  aint   | 256  | yes  |  43.93 ms |     10x |
|Regular|   int   |  1   | yes  |  141.1 ms |    3.1x |
|Regular|   int   |  2   | yes  |  70.78 ms |    6.2x |
|Regular|   int   |  4   | yes  |  36.11 ms |     12x |
|Regular|   int   |  8   | yes  |  19.31 ms |     23x |
|Regular|   int   |  16  | yes  |  11.78 ms |     37x |
|Regular|   int   |  32  | yes  |  10.33 ms |     43x |
|Regular|   int   |  64  | yes  |  18.93 ms |     23x |
|Regular|   int   | 128  | yes  |  36.09 ms |     12x |
|Regular|   int   | 256  | yes  |  55.64 ms |    7.9x |

### CODE REVIEW

**Comment by henryiii** [comment]
Had to reduce axis size to 16, MSVC couldn't handle it:

```
extern/mpl/include\boost/mpl/iter_fold_if.hpp(90): fatal error C1060: compiler is out of heap space
```

**Comment by HDembinski** [comment]
Wow! What is causing this an `axis::variant` with more than 16 types? That seems weird, I would assume that the variant can support many more. I know of other implementations that support hundreds of types. `boost::variant2` is currently in review, it can solve this issue.

**Comment by henryiii** [comment]
The variant is okay, it’s the fill expansion that’s happening to support all of the different fill arguments . I do that roughly twice as much as in the original version, because every histogram now has a threaded fill.

**Comment by HDembinski** [comment]
Can you point to the code line? I don't know what you mean.

**Comment by henryiii** [comment]
Adding the following two fill helper classes:

* [include/boost/histogram/python/histogram_threaded.hpp](https://github.com/scikit-hep/boost-histogram/blob/henryiii-perf/include/boost/histogram/python/histogram_threaded.hpp)
* [include/boost/histogram/python/histogram_atomic.hpp](https://github.com/scikit-hep/boost-histogram/blob/henryiii-perf/include/boost/histogram/python/histogram_atomic.hpp)

Causes MSVC to die during the compile with an out-of-memory error when added:

https://github.com/scikit-hep/boost-histogram/blob/fea13c96e77833cad9d3c85b045dbf0e55babe41/src/histogram/histogram.cpp#L96-L106

Dropping the total allowed number of axes from 32 to 16:

https://github.com/scikit-hep/boost-histogram/blob/fea13c96e77833cad9d3c85b045dbf0e55babe41/include/boost/histogram/python/pybind11.hpp#L18-L21

Fixes the issue for now.

**Comment by henryiii** [comment]
I will probably need to add (optionally, depending on whether a storage supports them) a weighted and sampled and sampled and weighed fill, for each of regular and threaded fills. Still don't know how to add string based bin fills.

**Comment by henryiii** [comment]
>  `boost::variant2` is currently in review, it can solve this issue.

So that's why you wrote this in a way that would allow the backend variant to be swapped out... Sounds great as long as variant2 is also header only!

**Comment by HDembinski** [comment]
Yes, variant2 is header-only and has fewer dependencies on other Boost libs, in particular it is using mp11 instead of mpl.

I still don't understand why you get an error in boost.mpl. mp11 is not using mpl, since it is a replacement of mpl. The meta-function mp_with_index itself is tested with up to 64. So I guess somehow the error is still in boot.variant?

**Pull request merged**
