### PR TITLE
chore: try running tests with numpy 2

### PR DESCRIPTION
**Pull request by lgray**
I want to see if tests fail with the recently released numpy 2.

Related to #943

### CODE REVIEW

**Comment by lgray** [comment]
@henryiii can you please let these tests run so we can see what fails in numpy2?

**Comment by henryiii** [comment]
`numpy>=2.0.0b1` is already present in the tests, so pretty sure this does work.

**Comment by lgray** [comment]
I do not understand how the tests are passing:
https://github.com/scikit-hep/boost-histogram/blob/develop/tests/test_axis.py#L696-L700

Requires everything to be as expected, but:
```
>>> bh.axis.Integer(1, 3).edges
array([3., 3., 3.])
```

Something is rather fishy.

**Comment by lgray** [comment]
Likewise:
```
>>> a = bh.axis.Integer(-1, 3)
>>> a
Integer(3, 3)
>>> a == (-1,0,1,2)
False
```

**Pull request closed without merging**
