### PR TITLE
introducing try_cast

### PR DESCRIPTION
**Pull request by HDembinski**
try_cast behaves somewhat like a visitor for pybind11::objects.

### CODE REVIEW

**Comment by henryiii** [comment]
Two changes that I can do later:

* I don't like `[&]`, it's better to list the items captured explicitly
* This should be in its own header or in the histogram header, since not all .cpp files will use it and it's best to avoid extra work for the compiler if possible. (Plus it is cleaner)

Otherwise, it looks great.

**Comment by henryiii** [comment]
Also, the boost variant includes should be removed. Not that it changes much now, but it's cleaner and better if Boost::Histogram changes to a new variant impl.

**Comment by HDembinski** [comment]
> Two changes that I can do later:
> 
>     * I don't like `[&]`, it's better to list the items captured explicitly

Fair enough. I can fix this.

>     * This should be in its own header or in the histogram header, since not all .cpp files will use it and it's best to avoid extra work for the compiler if possible. (Plus it is cleaner)

Ok, what name do you suggest?

**Comment by henryiii** [comment]
Naming header files after what they have in them is always good. :)

**Comment by henryiii** [comment]
That looks fantastic, thanks!

**Pull request merged**
