### PR TITLE
Fix fill issues

### PR DESCRIPTION
**Pull request by HDembinski**
Fixes the issues in #214 reported by @nsmith-
- [x] `h.fill("foo")` must work
- [x] `h.fill(np.array("foo"))` should not work and give a clear error message (ndim==0 not supported)
- [ ] segfault of the following code
```py
h = bh.Histogram(bh.axis.StrCategory([], growth=True), bh.axis.Integer(0, 1))
h.fill(["a"], [1, 2])
```

### CODE REVIEW

**Comment by HDembinski** [comment]
Notes:
- segfault only:
  - when StrCategory (other axes work)
  - growth is on
  - argument for the category axis has a single entry
- bugs get hot-fixes for now, but the underlying issues in boost::histogram need to be fixed before the 1.72-beta closes

**Comment by HDembinski** [comment]
Henry if you want, you can merge this now and I make another PR for the segfault. I think I need to fix this in boost::histogram, there is nothing I can do on this level.

**Comment by henryiii** [comment]
Why is the gil release removed?

**Comment by HDembinski** [comment]
> Why is the gil release removed?

It still had my comment whether this is safe or not without an answer. So I was thinking about it again. If another thread resizes the array while we are processing it, the code will segfault. I think you argued the last time we discussed this, that this is acceptable - users should not modify an array in one thread and read it in another thread without a mutex.

**Comment by HDembinski** [comment]
I can revert this, but we need a proper comment otherwise I will stumble over this again.

**Comment by henryiii** [comment]
This is the same behavior as numpy. If you do not release the GIL, the Python interpreter locks up and will do *nothing* else; it can't even context-switch because it can't pause the call like it can with a series of Python commands. You should never make a potentially long-running call that holds the GIL.

A proper comment would be helpful.

**Comment by henryiii** [comment]
And users can always use shared memory and multithreading to get around a GIL lock. It's not a promise of thread safety. It's just a workaround to allow Python reference counting. We should not be changing that in the fill function (and I don't think we are).

**Comment by HDembinski** [comment]
Ah, so we should only release the gil when we do not manipulate the ref counts anymore, correct?

**Comment by henryiii** [comment]
Yes. If we change a refcount with the GIL released, that's a bug.

**Comment by HDembinski** [comment]
feel free to merge, i am not sure how fast i can provide the segfault fix and it makes no sense for this pr to wait

**Comment by henryiii** [comment]
Looks great, thanks!

**Pull request merged**
