### PR TITLE
Adding CI

### PR DESCRIPTION
**Pull request by henryiii**
This adds CI with Azure. Also adds setup.py support, and some warning fixes.

I'm testing a couple of versions of setup.py Python per platform (macOS, Linux, and Windows), and running the CMake build on a Linux node. The CMake one is a bit trickier to run with multiple Pythons, since its hard to get the python executable path in the recipe in a completely shell independent way.

### CODE REVIEW

**Comment by henryiii** [comment]
@eduardo-rodrigues Could you give me the ability to add projects in Azure for SciKit-HEP and/or add this project to it? Thanks!

**Comment by eduardo-rodrigues** [comment]
I still need to give you full rights and all that, but it seems a minimal set-up got committed at https://github.com/scikit-hep/boost-histogram/pull/6.

**Comment by eduardo-rodrigues** [comment]
I added you as administrator. Can you browse all fine, @henryiii?

Please add @HDembinski yourself. This way we check the settings are OK :-).

**Comment by henryiii** [comment]
That minimal setup basically assumes a pure python package. I'll try to retrigger this one.

**Comment by henryiii** [comment]
ToDo: add verbose build output.

**Comment by henryiii** [comment]
I've added more warning checking and some warning fixes from the #3 addition to develop as part of this PR, as well.

**Pull request merged**
