### PR TITLE
feat: support conversion, AxesTuple subclass, get/setattr

### LINKED ISSUE #430: name/title system
I'd like to propose upstreaming @LovelyBuggies fantastic title/name system from Hist to boost-histogram. There are several reasons for this:

* It has no dependencies
* It can take part in #423 in providing a consistent API for uproot and mplhep (maybe others) (`mplhep.plothist(uproot.to_boost())` would show titles too, like Hist, and @jpivarski probably could add the same api directly to TH* objects in Uproot4)
* It can make dict-indexing, projections, and axes read more clearly if names are used, allowing a high level of clarity as to which axis is being referenced.
* It is completely optional, and does not affect the current usage at all
* It would make conversions to/from hist easier, since currently names and titles get packed into a dict, which then has to be changed going between hist/boost-histogram (especially for uproot, since title and name have to be handled during the conversion)
* We can optimize the storage internally, just keeping the strings directly in the metadata type, rather than storing python dicts and python strings

Quick example of usage:

```python
h = bh.Histogram(
    bh.axis.Regular(10, -1, 1, name="x"),
    bh.axis.Regular(20, -2, 2, name="y"),
)
h.fill(x=np.random.normal(size=1_000_000), y=np.random.normal(size=1_000_000))

h.project("y");

h[{"x": sum, "y": bh.rebin(2)}]

h.axes["x"].label = "x [μm]"
h.axes["y"].label = "y [cm]"
mplhep.hist2dplot(h);
```

The proposed design, open for discussion:

* Axes gain a new `name` parameter.
    * This probably should be a read-only parameter (which is not how Hist currently works)
    * When histograms are created, they make sure all names are ether empty or unique
    * Names are used anywhere axis numbers can be used.
        * Empty-name axes must be accessed by number.
* Axes gain a new `label` parameter
   * Will override the name for plotting libraries, so titles can be attached to the histogram rather than added afterwords in the plot.
    * If the label is not set, the name is used if available.
* The metadata slot in boost-histogram's C++ becomes a struct, with two strings and an arbitrary Python object.

@HDembinski, what do you think?

### PR DESCRIPTION
**Pull request by henryiii**
Adding an involved test that looks "Hist"-like, to make sure functionality Hist relies on is tested, like the ability to override AxesTuple with a subclass. Closes #430, as @HDembinski doesn't want name lookup in boost-histogram, at least for the foreseeable future.

Due to the design, adding custom functionality like a read only name is actually quite easy - subclasses just need to access `._ax.metadata` directly. Didn't need a change, just a test.

Adds a simple hook that allows customizations of the conversion process by subclasses.

Adds `ax.axes.<anything>` as a proxy for `ax.<anything>`, making "metadata" no longer special here either.

### CODE REVIEW

**Comment by HDembinski** [comment]
The reason to drop the cpp interface was to simplify the code and make the extra wrapping and indirection obsolete. I don't see that happening here, as you continue to rely on that the set_family feature.

**Comment by HDembinski** [comment]
Other people should wrap boost-histogram by subclassing or via composition.

**Comment by henryiii** [comment]
Dropping CPP did simplify quite a bit, and removed the `Base*` classes, etc. (see #402). It was never supposed to or able to remove casting / set_family, since:

```python
oax = CustomIntCategory(growth=True)
h = CustomHist(oax)
h.fill([1,2,3])
(ax,) = h.axes
```

What is `ax`? It's not even the same object as `oax`. Boost-histogram leaves this completely up to Boost.Histogram, and "casts" the cpp instance to Python when it is needed; when it does that, it has to know what to cast parts to. If Boost.Histogram adds any features to remove flow bins or change axes types, this system will be forward compatible with that.

There is a way to replace this: you could track through all types through all boost-histogram operations and manually map types; you would also have to keep the type objects stored in the hist object (this also is needed for all other boost-histogram classes, like transforms and storages). The other useful feature is that you can convert between histogram libraries naturally (`Hist(th1.to_bh())` for example), and all axes get generated in the new family instead of the old one; if this didn't exist, you'd have to create and apply a mapping of boost-histogram <-> custom classes.

At the moment, that replacement would a very significant change, and could possibly be more error prone (at least would be more manual code / dict building) for a user library to set up than a simple decorator. A nice documentation page on how to do this might be better than trying to replace the system with another system with more manual intervention.

Also, this _is_ subclassing; the family feature just enables consistent return types. If you only change Histogram, you don't need to add families; it's only for subclasses Axes, etc. (Since everyone will likely want to add names, I expect everyone will need to subclass at least Axes, though). You can't use composition because the underlying parts are in C++; templated C++ at that, so users cannot actually add a new Axes or subclass the C++ axes in C++; it wouldn't make a valid `histogram<...>`.

**Comment by HDembinski** [comment]
Ok, I think I understand, but this bothers me a bit. Perhaps it could be made so that the C++ code actually knows whether you pass a subclassed Axis. We can already store arbitrary metadata in the metadata field, so in principle we could also store the subclassing info.

**Pull request merged**
