### PR TITLE
Henryiii macos 10.14.4

### PR DESCRIPTION
**Pull request by henryiii**
Fixing a warning for macOS 10.14.4, and making warnings as errors optional (really only needed for CI).
Also adding a standard metadata type (could be changed from a string eventually).

### CODE REVIEW

**Comment by HDembinski** [comment]
Hi Henry, you could use a Python string directly as the metadata.

**Comment by henryiii** [comment]
An std::string is about the same, and a bit more natural for c++ for now. I need to see if Unicode support for example is better with a python string though.

**Comment by HDembinski** [comment]
? But this is a Python module, why would you want to translate back and forth between a Python string and std::string.

**Comment by HDembinski** [comment]
Unicode will definitely work better with a Python string. And you don't have to convert anything when users construct their axis types.

**Comment by HDembinski** [comment]
This is one of those situations where it is actually useful that you can chose the metadata type statically to whatever you like.

**Comment by henryiii** [comment]
Yes, you are right. Since I don’t need the value in C++ it’s better to use py::str.

**Comment by henryiii** [comment]
I am considering the possibility of allowing our user to attach any py object, as that way you could attach a dictionary of information or something like that, maybe units.  I initially made a custom struct to make sure that I caught all of the places that needed changing.

**Comment by HDembinski** [comment]
That would be cool as well, and it is basically the same performance. Then you would use a pybind11::object instead of pybind11::str, I think.

**Comment by henryiii** [comment]
I will probably rename this to metadata again, just to keep the API is similar to B::H as possible, and because I now allow arbitrary python to be attached.  Hist will probably call this label.

**Comment by HDembinski** [comment]
Yes, I like that also better.

**Pull request merged**
